-- Initialize Sakila test database schema and data
-- This script creates the film table and populates it with test data
-- that matches the expectations from the acceptance tests

-- Create film table
CREATE TABLE IF NOT EXISTS film (
    film_id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);

-- Clear any existing data
TRUNCATE TABLE film RESTART IDENTITY;

-- Insert test data for films starting with 'A' (46 films expected)
INSERT INTO film (title) VALUES
('ACADEMY DINOSAUR'), ('ACE GOLDFINGER'), ('ADAPTATION HOLES'), ('AFFAIR PREJUDICE'), 
('AFRICAN EGG'), ('AGENT TRUMAN'), ('AIRPLANE SIERRA'), ('AIRPORT POLLOCK'), 
('ALABAMA DEVIL'), ('ALADDIN CALENDAR'), ('ALAMO VIDEOTAPE'), ('ALASKA PHANTOM'), 
('ALI FOREVER'), ('ALICE FANTASIA'), ('ALIEN CENTER'), ('ALLEY EVOLUTION'), 
('ALONE TRIP'), ('ALTER VICTORY'), ('AMADEUS HOLY'), ('AMELIE HELLFIGHTERS'), 
('AMERICAN CIRCUS'), ('AMISTAD MIDSUMMER'), ('ANACONDA CONFESSIONS'), ('ANALYZE HOOSIERS'), 
('ANGELS LIFE'), ('ANNIE IDENTITY'), ('ANONYMOUS HUMAN'), ('ANTHEM LUKE'), 
('ANTITRUST TOMATOES'), ('ANYTHING SAVANNAH'), ('APACHE DIVINE'), ('APOCALYPSE FLAMINGOS'), 
('APOLLO TEEN'), ('ARABIA DOGMA'), ('ARACHNOPHOBIA ROLLERCOASTER'), ('ARMAGEDDON LOST'), 
('ARMY FLINTSTONES'), ('ARSENIC INDEPENDENCE'), ('ARTIST COLDBLOODED'), ('ATLANTIS CAUSE'), 
('ATTACKS HATE'), ('ATTRACTION NEWTON'), ('AUTUMN CROW'), ('AVIATOR POLLOCK'), 
('AWAKENINGS BED'), ('AWESOME GUMP');

-- Insert test data for films starting with 'B' (54 films expected)
INSERT INTO film (title) VALUES
('BABE GOLDFINGER'), ('BABYLON DIARY'), ('BACKLASH UNDEFEATED'), ('BADMAN DAWN'), 
('BAG CALMNESS'), ('BALLOON HOMEWARD'), ('BALLROOM MOCKINGBIRD'), ('BANGBANG CITIZEN'), 
('BARBARELLA STREETCAR'), ('BAREFOOT CHOCOLAT'), ('BASIC EASY'), ('BEACH HEARTBREAKERS'), 
('BEAN LOVELY'), ('BEAR GRACELAND'), ('BEAST HUNCHBACK'), ('BEAUTY GREASE'), 
('BED HIGHBALL'), ('BEDAZZLED MARRIED'), ('BEDKNOBS PERSPECTIVE'), ('BEETHOVEN EXORCIST'), 
('BEHOLDER SEAGAL'), ('BELOVED CHOCOLAT'), ('BENEATH RUSH'), ('BERETS AGENT'), 
('BEST WORST'), ('BEVERLY OUTLAW'), ('BICYCLE CREDIT'), ('BILL OTHERS'), 
('BINGO TALENTED'), ('BIRCH ANTITRUST'), ('BIRD INDEPENDENCE'), ('BIRDCAGE CASPER'), 
('BIRDS PERDITION'), ('BLACKOUT PRIVATE'), ('BLADE POLISH'), ('BLANKET BEVERLY'), 
('BLINDNESS GUN'), ('BLOOD ARGONAUTS'), ('BLUES INSTINCT'), ('BOARDED DARES'), 
('BOAT BANK'), ('BODIES DISOBEDIENCE'), ('BONNIE HOLOCAUST'), ('BOOGIE AMELIE'), 
('BOONDOCK BALLROOM'), ('BORN SPINAL'), ('BORROWERS BEDAZZLED'), ('BOULEVARD MOB'), 
('BOUND CHEAPER'), ('BOXER CLIMAX'), ('BRANNIGAN SUNRISE'), ('BRAVEHEART HUMAN'), 
('BREAD DAISY'), ('BREAKING HOME');

-- Insert test data for films starting with 'C' (58 films expected)
INSERT INTO film (title) VALUES
('CABIN FLASH'), ('CADDYSHACK JEDI'), ('CALENDAR GUNFIGHT'), ('CALIFORNIA BIRDS'), 
('CAMELOT VACATION'), ('CAMPUS REMEMBER'), ('CANDIDATE PERDITION'), ('CANDLES GRAPES'), 
('CANYON STOCK'), ('CAPER MOTIONS'), ('CAPTAIN FLYBOYS'), ('CARRIE BUNCH'), 
('CASABLANCA SUPER'), ('CASE NIGHTMARE'), ('CASSIDY WYOMING'), ('CASUALTIES ENCINO'), 
('CAT CONEHEADS'), ('CATCH ALADDIN'), ('CATWOMAN COMA'), ('CAUSE DATE'), 
('CELEBRITY HORN'), ('CENTER DINOSAUR'), ('CHAINSAW UPTOWN'), ('CHAMBER ITALIAN'), 
('CHAMPION FLATLINERS'), ('CHANCE RESURRECTION'), ('CHAPLIN LICENSE'), ('CHARADE DUFFEL'), 
('CHARIOTS CONSPIRACY'), ('CHASING FIGHT'), ('CHEAPEST HUNG'), ('CHICAGO NORTH'), 
('CHICKEN HELLFIGHTERS'), ('CHILL LUCK'), ('CHINATOWN GLADIATOR'), ('CHISUM BEHAVIOR'), 
('CHITTY LOCK'), ('CHOCOLAT HARRY'), ('CHRISTMAS MOONSHINE'), ('CHRONICLE VARGAS'), 
('CINCINATTI WHISPERER'), ('CITIZEN SHREK'), ('CITRUS CHILL'), ('CITY CASPER'), 
('CLAMPETT COMFORTS'), ('CLEOPATRA DEVIL'), ('CLERKS ANGELS'), ('CLOCKWORK PARADISE'), 
('CLONES PINOCCHIO'), ('CLOSER BANG'), ('CLUE GRAIL'), ('CLUBS ARIEL'), 
('CLYDE THEORY'), ('COAST RAINBOW'), ('COCKTAIL CASUALTY'), ('COCO JACKET'), 
('COLLISION STRANGER'), ('COLOR PHILADELPHIA');

-- Insert a few test films for other letters to test edge cases
INSERT INTO film (title) VALUES
('DANCING FEVER'), ('EAGLE LOVERBOY'), ('FAMILY SWEET'), ('GASOLINE DUDE'),
('HAMLET WISDOM'), ('ICE CROSSING'), ('JACKET FRISCO'), ('KARATE MOON'),
('LABOR TRACY'), ('MAGIC MALLRATS'), ('NATURAL STOCK'), ('OCEAN THIRTEEN'),
('PACIFIC AMISTAD'), ('QUEEN LUKE'), ('RADIO JACK'), ('SATURDAY LAMBS'),
('TAXI KICK'), ('UNFAITHFUL KILL'), ('VALLEY PACKER'), ('WAGON JAWS'),
('YOUNG LANGUAGE'), ('ZION GARDEN');

-- Create index on title for performance (as expected by acceptance tests)
CREATE INDEX IF NOT EXISTS idx_film_title ON film(title);

-- Verify the data
SELECT 
    LEFT(title, 1) as starting_letter, 
    COUNT(*) as film_count 
FROM film 
WHERE LEFT(title, 1) IN ('A', 'B', 'C')
GROUP BY LEFT(title, 1) 
ORDER BY starting_letter; 