services:
  postgres:
    image: 'sakiladb/postgres:latest'
    container_name: sakila-postgres
    environment:
      POSTGRES_DB: sakila
      POSTGRES_USER: sakila
      POSTGRES_PASSWORD: sakila
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sakila -d sakila"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - sakila_data:/var/lib/postgresql/data
      - ./docker/postgres/setup-password.sh:/setup-password.sh
    entrypoint: ["/setup-password.sh"]
    networks:
      - sakila-network

volumes:
  sakila_data:
    driver: local

networks:
  sakila-network:
    driver: bridge 